apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: devsearch-cicd
  title: GitLab Saas (LINX)
  description: |
    Create a fresh code repository
    - Mirrors your repositories
    - create a CI/CD pipeline
    - For more info, view [User Guide](https://helloworld.com)
  tags:
    - gitlab
spec:
  owner: user:guest
  type: TruPipeline
  
  parameters:
    - title: Create a Build Pipeline
      required:
        - app
        - appName
        - sourceCodeRepoUrl
      errorMessage:
        properties:
          appName: "Must be alphanumeric, '_', or '-'"
          sourceCodeRepoUrl: "Must be a valid URL"
      properties:
        info:
          type: "null"
          description: |
            ### Requet access to GitLab SAAS
            ### Add SV-MAGLEV-DEV as maintainer
        migrateApp:
          title: Migrate app to GitLab SaaS
          type: boolean
          description: if selected. the existing on-prem repo will be copied to GitLab Saas and archived
          default: false
          ui:field: ConditionalCheckboxWithModalField
          ui:options:
            visibilityExpression: "{{ parameters.isLegacyRepo and not parameters.createPipeline and not parameters.isAppMigrated}}"
            modalTitle: "Migrate App to GitLab SaaS?"
            modalContent: "Are you sure you want to migrate to GitLab Saas?"
            modalConfirmText: "Yes, let's go"
            modalCancelText: "No, I want to create a new repository"
            requireModalConfirmation: true
            showModalOnCheck: true
        gitlabProjectId:
          ui:widget: hidden
          type: string          
        createPipeline:
          ui:widget: hidden
          type: boolean
          default: true  
        appOwner:
          ui:widget: hidden
          type: string
        app:
          title: ServiceNow App   
          ui:field: AppPicker
          ui:options:
            enabledDependsOn: createPipeline
            requireCloudAccount: hidden
        appName:
          title: App Name
          type: string
          pattern: "^[a-zA-Z0-9_-]+$"
          description: This name will be used as the GitLab repository Name
          ui:field: ConditionalTextField
          ui:options:
            enabledDependsOn: createPipeline
        platform:
          title: Platform
          type: string
          enum:
            - dotnet
            - java
            - nodejs
            - generic
          ui:enumNames:
            - .Net Core
            - Java
            - NodeJS
            - Generic
          default: generic
        isLegacyRepo:
          title: Mirror an existing Application
          type: boolean
          description: Select to move to legacy repo to Gitlab cloud
          default: false
          ui:field: ConditionalTextField
          ui:options:
            visibilityExpression: "{{ parameters.createPipeline}}"
        allowGitHistory:

          title: Allow importing git history
          type: boolean
          default: false
          description: Select if you need to import git history from previous repository
          ui.filed: ConditionalTextField
          ui.options: 
            visibilityExpression: "{{ not paramters.isLegacyRepo }}"
        sourceCodeRepoUrl:
          title: Source Code Repository URL
          type: string          
          description: The URL of the source code repository to mirror
          ui:field: ConditionalTextField
          ui:options:
            enabledDependsOn: createPipeline
            visibilityExpression: "{{ parameters.isLegacyRepo}}"
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./mulesofttemplate
        values:
          name: ${{ parameters.name }}
  
    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'
  
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        
    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - user:default/guest
        title: 'Template executed'
        info: 'Your template has been executed'
        severity: 'normal'
  
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
