apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: devsearch-cicd
  title: GitLab Saas (LINX)
  description: |
    Create a fresh code repository
    - Mirrors your repositories
    - create a CIC pipeline 
    - For more info, view [User Guide](https://helloworld.com)
tags:
  - gitlab
spec:
  owner: user:guest
  type: TruPipeline

  parameters:
    - title: Create a Build Pipeline
      required:
        - app
        - appName
        - sourceCodeRepoUrl
      errorMessage: 
        properties:
          appName: "Must be alphanumeric, '_', or '-'"
          sourceCodeRepoUrl: "Must be a valid URL"
      properties:
        info:
          type: "null"
          description: | ...
        migrateApp: ...
        gitlabProjectId: ...
        createPipeline: ...
        appOwner:
          ui:widget: hidden
          type: string
        app:
          title: App Name
          type: string
          pattern: "^[a-zA-Z0-9_\\-]+$+"
          description: This name will be used as the GItLab repository Name
          ui:Field: ConditionalTextField
          ui:options:
            enabledDependsOn: createPipeline
        Platform:
          title: Platform
          type: string
          enum: ...
          ui.enumNames:
            - .Net Core
            - Java
            - NodeJS
          default: generic
        isLegacyRepo:
          title: Is Legacy Repository
          type: boolean
          description: Check if this is a legacy repository
          default: false
          ui.Field: ConditionalTextField
          ui.options:
            visibilityExpression: "{{ parameters.createPipeline}}" 
          
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./mulesofttemplate
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    - id: register
      name: Register
      action: catalog:register
      input:
          repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
          catalogInfoPath: '/catalog-info.yaml'
          
    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - user:default/guest
        title: 'Template executed'
        info: 'Your template has been executed'
        severity: 'normal'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}